### ISSUE TITLE
Link in README not working

### ISSUE THREAD

**Issue by Shivang-Bhandari** [jaikathuria/SongCatalog#1]
Check the link mentioned at the bottom of the README

**Comment by Shivang-Bhandari** [comment]
http://ec2-52-33-52-40.us-west-2.compute.amazonaws.com/

**Comment by jaikathuria** [comment]
🤣 Pata hai 
This is because, @udacity closes the instance of the machine they have provided as soon as you GRADUATE 
from FULL STACK NANODEGREE.
@Shivang-Bhandari Challo koi baat nahi.

**Comment by Shivang-Bhandari** [comment]
fir link hata de
